---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lyz.
--- DateTime: 17/09/2022 14:53
---
---

function descriptor()
    return {
        title = "Hello Title",
        version = "0.1",
        author = "Adelyne",
        shortdesc = "➡📂 Move to folder",
        description = "To easily move current playing file to another folder.",
        capabilities = {}
    }
end

function activate()
    d = vlc.dialog("📂 Move to folder")

    user_data_dir = vlc.config.userdatadir()
    saved_paths_filename = user_data_dir .. "move_to_folder_paths.txt"
    local file_read = io.open(saved_paths_filename,"r")
    paths = {"","","","",""}
    if file_read then
        i = 1
        for line in file_read:lines() do
            paths[i] = line
            i = i + 1
        end
        file_read:close()
    end

    d:add_label("📁 Folder path", 2, 1)

    line = 1
    r1_folder_path_input = d:add_text_input(paths[line], 2, line+1)
    r1_move_button = d:add_button("➡ Move to folder", r1_move_to_folder, 1, line+1)

    line = line + 1
    r2_folder_path_input =d:add_text_input(paths[line], 2, line+1)
    r2_move_button = d:add_button("➡ Move to folder", r2_move_to_folder, 1, line+1)

    line = line + 1
    r3_folder_path_input = d:add_text_input(paths[line], 2, line+1)
    r3_move_button = d:add_button("➡ Move to folder", r3_move_to_folder, 1, line+1)

    line = line + 1
    r4_folder_path_input = d:add_text_input(paths[line], 2, line+1)
    r4_move_button = d:add_button("➡ Move to folder", r4_move_to_folder, 1, line+1)

    line = line + 1
    r5_folder_path_input = d:add_text_input(paths[line], 2, line+1)
    r5_move_button = d:add_button("➡ Move to folder", r5_move_to_folder, 1, line+1)

    line = line + 1
    r6_folder_path_input = d:add_text_input(paths[line], 2, line+1)
    r6_move_button = d:add_button("➡ Move to folder", r6_move_to_folder, 1, line+1)

    error_label = d:add_label("ℹ Sucess/Fail text will appear here.", 2, line+2)

    d:show()
end

function r1_move_to_folder()
    move_to_folder(r1_folder_path_input)
end

function r2_move_to_folder()
    move_to_folder(r2_folder_path_input)
end

function r3_move_to_folder()
    move_to_folder(r3_folder_path_input)
end

function r4_move_to_folder()
    move_to_folder(r4_folder_path_input)
end

function r5_move_to_folder()
    move_to_folder(r5_folder_path_input)
end

function r6_move_to_folder()
    move_to_folder(r6_folder_path_input)
end

function move_to_folder(folder_path_input)
    folder_path = folder_path_input:get_text()
    if folder_path:len() > 0 then
        item_id = vlc.playlist.current()
        item = vlc.input.item()
        file_path = vlc.strings.decode_uri(string.gsub(item:uri(), "^file:///", ""))
        file_name = file_path:match("([^/]+)$")
        file_folder = file_path:match("(.*/)")

        if string.find(folder_path,":/") then
            final_folder_path = folder_path
        else
            final_folder_path = file_folder .. folder_path
        end
        if final_folder_path:sub(-1) ~= "/" then
            final_folder_path = final_folder_path .. "/"
        end
        destination_file_path = final_folder_path .. file_name

        vlc.playlist.stop()
        sleep(5)
        vlc.playlist.delete(item_id)

        t = vlc.io.readdir(final_folder_path)
        if (t == nil) then
            os.execute('mkdir "'..final_folder_path..'"')
        end
        retval, err = os.rename(file_path, destination_file_path)

        vlc.msg.info("File : " .. file_path)
        vlc.msg.info("Destination : " .. destination_file_path)
        if (retval == nil) then
            vlc.msg.err("Fail: " .. err)
            error_label:set_text("⚠ Fail: " .. err)
        else
            error_label:set_text("✔ Sucess: " .. file_name)
        end
        vlc.playlist.play()
    end
end

function save_paths()
    local file_write = io.open(saved_paths_filename,"w")
    if file_write then
        file_write:write(r1_folder_path_input:get_text().."\n")
        file_write:write(r2_folder_path_input:get_text().."\n")
        file_write:write(r3_folder_path_input:get_text().."\n")
        file_write:write(r4_folder_path_input:get_text().."\n")
        file_write:write(r5_folder_path_input:get_text().."\n")
        file_write:write(r6_folder_path_input:get_text().."\n")
        file_write:close()
    end
end

function deactivate()
    save_paths()
    d:delete()
end

function close()
    vlc.deactivate()
end


function sleep(s)
    local ntime = os.clock() + s/10
    repeat until os.clock() > ntime
end

function meta_changed()
    save_paths()
end